/**
 * Entity Editor Component
 * Dynamic form based on entity type
 */

function showNewEntityModal(type = 'event') {
  state.set('selectedEntity', null);
  showEntityEditor(type, null);
}

async function editEntity(id) {
  try {
    const entity = await api.getEntity(id, { include_metadata: 'auto' });
    state.set('selectedEntity', entity);
    showEntityEditor(entity.entity_type, entity);
  } catch (error) {
    console.error('Failed to load entity:', error);
    toast.error('Failed to load entity');
  }
}

function showEntityEditor(type, entityData) {
  const modal = document.getElementById('entity-modal');
  const title = document.getElementById('entity-modal-title');
  const body = document.getElementById('entity-modal-body');

  title.textContent = entityData ? `Edit ${type}` : `New ${type}`;

  // Render form based on type
  body.innerHTML = renderEntityForm(type, entityData);

  // Show modal
  modal.classList.remove('hidden');

  // Setup form handlers
  setupEntityFormHandlers(type, entityData);
}

function renderEntityForm(type, data) {
  if (type === 'event') {
    return renderEventForm(data);
  } else if (type === 'character') {
    return renderCharacterForm(data);
  } else if (type === 'fiction') {
    return renderFictionForm(data);
  } else {
    return renderGenericForm(type, data);
  }
}

function renderEventForm(data) {
  return `
    <form id="entity-form">
      <div class="tabs">
        <ul class="tab-list">
          <li><button type="button" class="tab-button active" data-tab="basic">Basic Info</button></li>
          <li><button type="button" class="tab-button" data-tab="phases">Phases</button></li>
          <li><button type="button" class="tab-button" data-tab="facts">Facts</button></li>
          <li><button type="button" class="tab-button" data-tab="participants">Participants</button></li>
        </ul>
      </div>

      <div class="tab-content active" id="tab-basic">
        <!-- REMOVED: Event ID field - auto-generated by backend -->

        <div class="form-group">
          <label class="form-label">Timestamp</label>
          <input type="datetime-local" class="form-input" name="timestamp" value="${data?.timestamp || ''}" required>
        </div>

        <!-- NEW: Character dropdown with smart creation -->
        <div class="form-group">
          <label class="form-label">Characters Involved</label>
          <select class="form-select" id="character-select" name="character_id">
            <option value="">Loading characters...</option>
          </select>
          <div class="form-help">Select a character or create a new one</div>
        </div>

        <!-- NEW: Location dropdown with smart creation -->
        <div class="form-group">
          <label class="form-label">Location</label>
          <select class="form-select" id="location-select" name="location_id">
            <option value="">Loading locations...</option>
          </select>
          <div class="form-help">Select a location or create a new one</div>
        </div>

        <div class="form-group">
          <label class="form-label">Type</label>
          <select class="form-select" name="type">
            <option>information_transfer</option>
            <option>deception_event</option>
            <option>complex_multi_phase</option>
            <option>state_change</option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-label">Summary</label>
          <textarea class="form-textarea" name="summary" rows="3">${data?.summary || ''}</textarea>
        </div>
      </div>

      <div class="tab-content" id="tab-phases">
        <div id="phases-container">
          <button type="button" class="btn btn-secondary" id="add-phase-btn">+ Add Phase</button>
        </div>
      </div>

      <div class="tab-content" id="tab-facts">
        <div id="facts-container">
          <button type="button" class="btn btn-secondary" id="add-fact-btn">+ Add Fact</button>
        </div>
      </div>

      <div class="tab-content" id="tab-participants">
        <div id="participants-container">
          <button type="button" class="btn btn-secondary" id="add-participant-btn">+ Add Participant</button>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" onclick="closeEntityModal()">Cancel</button>
        <button type="submit" class="btn btn-primary">Save Event</button>
      </div>
    </form>
  `;
}

function renderCharacterForm(data) {
  // Reconstruct full name from parts if editing
  let fullName = '';
  if (data?.data) {
    const parts = [];
    if (data.data.first_name) parts.push(data.data.first_name);
    if (data.data.middle_name) parts.push(data.data.middle_name);
    if (data.data.last_name) parts.push(data.data.last_name);
    fullName = parts.join(' ');
    if (data.data.title) fullName += ', ' + data.data.title;
  } else if (data?.name) {
    fullName = data.name;
  }

  return `
    <form id="entity-form">
      <div class="form-group">
        <label class="form-label">Full Name</label>
        <input type="text" class="form-input" id="character-full-name" name="full_name" value="${fullName}" required>
        <div class="form-help" style="font-size: var(--font-size-xs); color: var(--color-gray-500); margin-top: var(--space-1);">
          <strong>Examples:</strong><br>
          "John Smith" → First: John, Last: Smith<br>
          "Mary Jane Watson" → First: Mary, Middle: Jane, Last: Watson<br>
          "Fred Andrew Wiggins, Dr." → First: Fred, Middle: Andrew, Last: Wiggins, Title: Dr.
        </div>
      </div>

      <!-- Hidden parsed fields -->
      <input type="hidden" name="first_name" id="char-first-name">
      <input type="hidden" name="middle_name" id="char-middle-name">
      <input type="hidden" name="last_name" id="char-last-name">
      <input type="hidden" name="title" id="char-title">

      <div class="form-group">
        <label class="form-label">Role</label>
        <select class="form-select" name="role">
          <option ${data?.data?.role === 'protagonist' ? 'selected' : ''}>protagonist</option>
          <option ${data?.data?.role === 'antagonist' ? 'selected' : ''}>antagonist</option>
          <option ${data?.data?.role === 'supporting' ? 'selected' : ''}>supporting</option>
          <option ${data?.data?.role === 'minor' ? 'selected' : ''}>minor</option>
        </select>
      </div>

      <div class="form-group">
        <label class="form-label">Age (optional)</label>
        <input type="number" class="form-input" name="age" value="${data?.data?.age || ''}">
      </div>

      <div class="form-group">
        <label class="form-label">Race/Ethnicity (optional)</label>
        <input type="text" class="form-input" name="race" value="${data?.data?.race || ''}">
      </div>

      <div class="form-group">
        <label class="form-label">Country/Nationality (optional)</label>
        <input type="text" class="form-input" name="country" value="${data?.data?.country || ''}">
      </div>

      <div class="form-group">
        <label class="form-label">Religion (optional)</label>
        <input type="text" class="form-input" name="religion" value="${data?.data?.religion || ''}">
      </div>

      <div class="form-group">
        <label class="form-label">Education Level (optional)</label>
        <select class="form-select" name="education_level">
          <option value="">Not specified</option>
          <option ${data?.data?.education_level === 'elementary' ? 'selected' : ''}>elementary</option>
          <option ${data?.data?.education_level === 'high_school' ? 'selected' : ''}>high_school</option>
          <option ${data?.data?.education_level === 'some_college' ? 'selected' : ''}>some_college</option>
          <option ${data?.data?.education_level === 'bachelors' ? 'selected' : ''}>bachelors</option>
          <option ${data?.data?.education_level === 'masters' ? 'selected' : ''}>masters</option>
          <option ${data?.data?.education_level === 'doctorate' ? 'selected' : ''}>doctorate</option>
          <option ${data?.data?.education_level === 'self_taught' ? 'selected' : ''}>self_taught</option>
        </select>
      </div>

      <div class="form-group">
        <label class="form-label">Career/Occupation (optional)</label>
        <input type="text" class="form-input" name="career" value="${data?.data?.career || ''}">
      </div>

      <div class="form-group">
        <label class="form-label">Skills & Talents (optional)</label>
        <textarea class="form-textarea" name="skills" rows="2">${data?.data?.skills || ''}</textarea>
        <div class="form-help">Comma-separated list (e.g., "Piano, Archery, Public Speaking")</div>
      </div>

      <div class="form-group">
        <label class="form-label">Physical Description (optional)</label>
        <textarea class="form-textarea" name="physical_description" rows="3">${data?.data?.physical_description || ''}</textarea>
      </div>

      <div class="form-group">
        <label class="form-label">Personality Traits (optional)</label>
        <textarea class="form-textarea" name="personality" rows="3">${data?.data?.personality || ''}</textarea>
      </div>

      <div class="form-group">
        <label class="form-label">Background (optional)</label>
        <textarea class="form-textarea" name="background" rows="3">${data?.data?.background || ''}</textarea>
      </div>

      <div class="form-group">
        <label class="form-label">Motivations (optional)</label>
        <textarea class="form-textarea" name="motivations" rows="3">${data?.data?.motivations || ''}</textarea>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" onclick="closeEntityModal()">Cancel</button>
        <button type="submit" class="btn btn-primary">Save Character</button>
      </div>
    </form>
  `;
}

function renderFictionForm(data) {
  return `
    <form id="entity-form">
      <!-- REMOVED: Fiction ID field - auto-generated by backend -->

      <div class="form-group">
        <label class="form-label">Name</label>
        <input type="text" class="form-input" name="name" value="${data?.name || ''}" required>
      </div>

      <div class="form-group">
        <label class="form-label">Description</label>
        <textarea class="form-textarea" name="description" rows="3">${data?.description || ''}</textarea>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" onclick="closeEntityModal()">Cancel</button>
        <button type="submit" class="btn btn-primary">Save Fiction</button>
      </div>
    </form>
  `;
}

function renderGenericForm(type, data) {
  return `
    <form id="entity-form">
      <div class="form-group">
        <label class="form-label">ID</label>
        <input type="text" class="form-input" name="id" value="${data?.id || ''}" required>
      </div>

      <div class="form-group">
        <label class="form-label">Name</label>
        <input type="text" class="form-input" name="name" value="${data?.name || ''}" required>
      </div>

      <div class="form-group">
        <label class="form-label">Description</label>
        <textarea class="form-textarea" name="description" rows="3">${data?.description || ''}</textarea>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" onclick="closeEntityModal()">Cancel</button>
        <button type="submit" class="btn btn-primary">Save Entity</button>
      </div>
    </form>
  `;
}

function setupEntityFormHandlers(type, data) {
  // Tab switching
  document.querySelectorAll('.tab-button').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('.tab-button').forEach(b => b.classList.remove('active'));
      document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));

      btn.classList.add('active');
      document.getElementById(`tab-${btn.dataset.tab}`).classList.add('active');
    });
  });

  // Character name parsing
  if (type === 'character') {
    const fullNameInput = document.getElementById('character-full-name');
    if (fullNameInput) {
      fullNameInput.addEventListener('blur', () => {
        const parsed = parseCharacterName(fullNameInput.value);
        document.getElementById('char-first-name').value = parsed.first_name;
        document.getElementById('char-middle-name').value = parsed.middle_name;
        document.getElementById('char-last-name').value = parsed.last_name;
        document.getElementById('char-title').value = parsed.title;
      });
    }
  }

  // Load dependency options if this is an event form
  if (type === 'event') {
    loadDependencyOptions('character', 'character-select');
    loadDependencyOptions('location', 'location-select');

    document.getElementById('character-select')?.addEventListener('change', () => {
      handleNewDependency('character', 'character-select');
    });

    document.getElementById('location-select')?.addEventListener('change', () => {
      handleNewDependency('location', 'location-select');
    });
  }

  // Form submission
  document.getElementById('entity-form').addEventListener('submit', async (e) => {
    e.preventDefault();
    await saveEntity(type, e.target);
  });
}

function parseCharacterName(fullName) {
  // Split on comma to extract title
  const [namePart, titlePart] = fullName.split(',').map(s => s.trim());

  // Split name into words
  const words = namePart.split(/\s+/).filter(w => w.length > 0);

  const result = {
    first_name: '',
    middle_name: '',
    last_name: '',
    title: titlePart || ''
  };

  if (words.length === 1) {
    result.first_name = words[0];
  } else if (words.length === 2) {
    result.first_name = words[0];
    result.last_name = words[1];
  } else if (words.length >= 3) {
    result.first_name = words[0];
    result.last_name = words[words.length - 1];
    result.middle_name = words.slice(1, -1).join(' ');
  }

  return result;
}

async function saveEntity(type, form) {
  const formData = new FormData(form);
  let data = Object.fromEntries(formData);
  const selectedEntity = state.get('selectedEntity');

  // Parse character name if needed
  if (type === 'character' && data.full_name) {
    const parsed = parseCharacterName(data.full_name);
    data = { ...data, ...parsed };
    delete data.full_name;
    // Set display name
    data.name = [parsed.first_name, parsed.middle_name, parsed.last_name]
      .filter(Boolean).join(' ') + (parsed.title ? ', ' + parsed.title : '');
  }

  try {
    let response;
    if (selectedEntity) {
      // EDITING: use entity ID from state
      response = await api.updateEntity(selectedEntity.id, data);
      toast.success('Entity updated');
    } else {
      // CREATING: data already wrapped by createEntity
      response = await api.createEntity(type, data);
      toast.success('Entity created');

      // Track for dependency callbacks
      if (response.data?.id) {
        window._lastCreatedEntityId = response.data.id;
      }
    }

    closeEntityModal();

    // Trigger dependency callback if exists
    if (window._dependencyCallback && response.data?.id) {
      window._dependencyCallback(response.data.id);
      window._dependencyCallback = null;
    }

    if (window.loadEntities) {
      loadEntities();
    }
  } catch (error) {
    console.error('Save failed:', error);
    toast.error('Failed to save entity');
  }
}

// ============================================================
// DEPENDENCY MANAGEMENT (Phase 6)
// ============================================================

/**
 * Load and populate dependency dropdowns
 */
async function loadDependencyOptions(type, selectId) {
  const select = document.getElementById(selectId);
  if (!select) return;

  try {
    const response = await api.request(`/entities?type=${type}&limit=1000`);
    const items = response.data || [];

    select.innerHTML = `
      <option value="">Select ${type}...</option>
      <option value="__new__">+ New ${capitalize(type)}</option>
    `;

    items.forEach(item => {
      const option = document.createElement('option');
      option.value = item.id;
      option.textContent = item.name;
      select.appendChild(option);
    });
  } catch (error) {
    console.error(`Failed to load ${type}s:`, error);
    select.innerHTML = `<option value="">Error loading ${type}s</option>`;
  }
}

/**
 * Handle "New X" selection
 */
function handleNewDependency(type, selectId) {
  const select = document.getElementById(selectId);

  if (select.value === '__new__') {
    showDependencyCreateChoice(type, (createdId) => {
      // Refresh dropdown and select new item
      loadDependencyOptions(type, selectId).then(() => {
        select.value = createdId;
      });
    });
    select.value = ''; // Reset
  }
}

/**
 * Show Quick vs Full Create choice
 */
function showDependencyCreateChoice(type, onCreated) {
  const overlay = document.createElement('div');
  overlay.className = 'modal-overlay';
  overlay.style.zIndex = '2100'; // Above main modal (which is at 2000)

  overlay.innerHTML = `
    <div class="modal-content" style="max-width: 500px;">
      <div class="modal-header">
        <h2 class="modal-title">Create ${capitalize(type)}</h2>
        <button class="modal-close" onclick="this.closest('.modal-overlay').remove()">&times;</button>
      </div>
      <div style="padding: var(--space-6);">
        <p class="text-gray" style="margin-bottom: var(--space-6);">
          How would you like to create this ${type}?
        </p>
        <div style="display: flex; gap: var(--space-4);">
          <button class="btn btn-primary" style="flex: 1;" onclick="quickCreateDependency('${type}', this)">
            Quick Create
            <div style="font-size: var(--font-size-xs); font-weight: normal; margin-top: 4px;">
              Just enter name
            </div>
          </button>
          <button class="btn btn-secondary" style="flex: 1;" onclick="fullCreateDependency('${type}', this)">
            Full Create
            <div style="font-size: var(--font-size-xs); font-weight: normal; margin-top: 4px;">
              Add all details
            </div>
          </button>
        </div>
      </div>
    </div>
  `;

  document.body.appendChild(overlay);
  window._dependencyCallback = onCreated;
  window._dependencyType = type;
}

/**
 * Quick Create - inline form
 */
async function quickCreateDependency(type, btn) {
  const overlay = btn.closest('.modal-overlay');
  const container = overlay.querySelector('.modal-content > div:last-child');

  container.innerHTML = `
    <form id="quick-create-form">
      <div class="form-group">
        <label class="form-label">${capitalize(type)} Name</label>
        <input type="text" class="form-input" name="name" required autofocus>
      </div>
      <div style="display: flex; gap: var(--space-3); justify-content: flex-end;">
        <button type="button" class="btn btn-secondary" onclick="this.closest('.modal-overlay').remove()">Cancel</button>
        <button type="submit" class="btn btn-primary">Create</button>
      </div>
    </form>
  `;

  container.querySelector('form').addEventListener('submit', async (e) => {
    e.preventDefault();
    const name = e.target.name.value;

    try {
      const response = await api.request('/entities', {
        method: 'POST',
        body: JSON.stringify({
          type: type,
          data: { name }
        })
      });

      toast.success(`${capitalize(type)} created`);
      overlay.remove();

      if (window._dependencyCallback) {
        window._dependencyCallback(response.data.id);
      }
    } catch (error) {
      console.error(`Failed to create ${type}:`, error);
      toast.error(`Failed to create ${type}`);
    }
  });
}

/**
 * Full Create - open full modal
 */
function fullCreateDependency(type, btn) {
  const overlay = btn.closest('.modal-overlay');
  const callback = window._dependencyCallback;

  overlay.remove();

  // Store callback and old save handler
  const oldSaveEntity = window.saveEntity;

  // Override saveEntity temporarily
  window.saveEntity = async function(entityType, form) {
    await oldSaveEntity(entityType, form);

    // After successful save, call callback with the created ID
    if (callback) {
      // Get the last created entity ID from response
      // We'll need to track this in the saveEntity function
      const lastCreatedId = window._lastCreatedEntityId;
      if (lastCreatedId) {
        callback(lastCreatedId);
      }
    }

    // Restore original handler
    window.saveEntity = oldSaveEntity;
  };

  // Open full entity editor
  showNewEntityModal(type);
}

function capitalize(str) {
  if (!str) return '';
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// ============================================================
// MODAL MANAGEMENT
// ============================================================

function closeEntityModal() {
  document.getElementById('entity-modal').classList.add('hidden');
}

// Modal close handlers
if (document.getElementById('entity-modal-close')) {
  document.getElementById('entity-modal-close').addEventListener('click', closeEntityModal);
}
